### ISSUE TITLE
Status Icon Colors do not get themed

### ISSUE THREAD

**Issue by jack-mil** [catppuccin/discord#283]
I see that the theme should change the status icon indicators by user avatars. However, Discord must have changed something, because the selectors in the source no longer work. 

**Example:** 
![image](https://github.com/catppuccin/discord/assets/62065280/b04cd245-f4e7-49fb-8db0-b44f4d5e73c1)

I have added the following to my custom CSS rules that seem to work for me (Macchiato):
```css
div[class^=avatar] rect[mask*=status-online] {
	fill: 	#a6da95;
}

div[class^=avatar] rect[mask*=status-dnd] {
	fill: 	#ed8796;
}

div[class^=avatar] rect[mask*=status-idle] {
	fill: 	#eed49f;
}
```
**Result:**
![image](https://github.com/catppuccin/discord/assets/62065280/2b37155f-6c69-4c4e-8ed7-6b2d2c364f17)

( Images from the Official Catppuccin Discord Server )
