### ISSUE TITLE
[BUG FIX] Small, niche fix for spoilered mentions

### ISSUE THREAD

**Issue by fowlis** [catppuccin/discord#30]
__Issue:__
The spoiler colour is the same colour as the background of a message mentioning the user
![](https://cdn.upload.systems/uploads/S24K8Bcg.gif)
![](https://cdn.upload.systems/uploads/OhZaE3gy.gif)
__Fix:__
This code changes the colour of a spoiler on a message mentioning the user
```css
.mentioned-Tre-dv .spoilerText-27bIiA.hidden-3B-Rum {
    background-color: red!important;
}
```
__Preview of fix:__
![](https://cdn.upload.systems/uploads/hjqaE3s6.gif)
(just to show that the code will only affect spoilered mentions)
![](https://cdn.upload.systems/uploads/W4zGdCz2.gif)
__Notes:__
I was going to PR this into the main.css, but I decided to just make it an issue in case the devs didn't want to merge it. After all, its a very niche fix and I don't think many users get pinged inside a spoiler for it to bother them
