### ISSUE TITLE
Latte profile cards & custom profile themes for all flavours are unreadable

### ISSUE THREAD

**Issue by Starcr0ss** [catppuccin/discord#307]
![image](https://github.com/catppuccin/discord/assets/26168814/f354c895-11e7-4d15-9ce9-8b77055f040c)
As you can see in the screenshot- I have to highlight my username, display name, and any status message (none here) to read it as it blends in with the background. I believe a new update broke this.

**Comment by ToxicAven** [comment]
This will be fixed in the future. Can you enable "Sync profile themes" in Settings -> A11y and see if that solves the problem until I can fix it fully?

**Comment by Starcr0ss** [comment]
> This will be fixed in the future. Can you enable "Sync profile themes" in Settings -> A11y and see if that solves the problem until I can fix it fully?

No such luck... Only thing that makes things *barely* readable is if you set the discord theme to dark, you'll get slightly darker text on a light background (still very difficult). It's not a big deal and I can patiently wait for a fix :)

**Comment by ToxicAven** [comment]
Ohhh this is a latte error, hm.

**Comment by RuiNtD** [comment]
From what I can tell, Discord puts a `theme-light` or `theme-dark` class on profiles based on the coloring of the profile, similar to what it puts on the `html` tag based on the user setting. It would probably make sense to just import Latte inside `.theme-light` in the dark themes. But since Discord can still use dark theme in light mode (dark theme profiles), would it make sense to only distribute dark themes and apply Latte on `theme-light`, which would apply if the user set their color theme to light, similar to what [cappuccin/opera-gx](https://github.com/catppuccin/opera-gx#-faq) does?

**Comment by Desoroxxx** [comment]
Any news or progress on this, it's even worse since the redesign
![image](https://github.com/user-attachments/assets/cc09140c-3582-4c38-b6c7-63a9587dae2a)

**Comment by sgoudham** [comment]
> Any news or progress on this, it's even worse since the redesign

I think @ToxicAven is unavailable at the moment so no one is currently looking at this.
More than happy to merge a PR from anyone willing to look into it with before/after screenshots highlighting the fix.

**Comment by Txaverria** [comment]
I was able to find and do the following:

Change the colors in the profile with some janky CSS:
![image](https://github.com/user-attachments/assets/fcf1f4f0-c1d8-4c02-b78a-c7dad0495609)

```CSS
/* Selects the tabs that have an aria-selected=true 
and all the tabs when they are hovered */
.theme-light .tabBarItem_ecc04c[aria-selected="true"],
.theme-light .tabBarItem_ecc04c:hover {
  border-bottom: 1px solid #11111b !important;
}

/* If in the .theme-light (profiles that have the issue using Catppuccin Mocha)
then edit out the following variables so that the text is readable */
.theme-light {
  --header-primary: #11111b; /* username - pronouns */
  --header-secondary: #11111b; /* Connections */
  --text-normal: #11111b; /* Most text */
}

/* Changes the color of the connected accounts section (like Spotify, Steam, etc.)
I found no other way to change it */
.theme-light .connectedAccounts_ab12c6 * {
  color: #11111b !important;
}
```

I found these variables, which I think if handled properly, could fix all issues at once, but I don't know how to use them:
![image](https://github.com/user-attachments/assets/f66a991e-680d-4378-87c1-54cdd5dc44b6)

But I couldn't change the flyout if you have a light theme in your own Discord profile.
![image](https://github.com/user-attachments/assets/6ae6d0a5-1b4f-4596-bafe-5bc5461f2a87)

Nor the 'Status' selected by the user:
![image](https://github.com/user-attachments/assets/6bd057eb-50ec-4ed1-9d02-072d4fecd9f3)
