### ISSUE TITLE
[ Feature Request ] Make threads stand out less

### ISSUE THREAD

**Issue by Ringlings** [catppuccin/discord#77]
Loving the theme, our one gripe with it is that the threads, while having rainbow colours looks cool, it makes them stand out too much from the other channels and sometimes we mistake them for unread threads. Is there any chance for an option or way to change this?

Example image:
![image](https://user-images.githubusercontent.com/110815694/203462865-c24880fe-ab92-47e5-b059-559c525b0e13.png)

**Comment by MatthiasGrandl** [comment]
I had the same issue. Add this to your custom CSS:

```css
ul[aria-label$=" threads"] > li:nth-child(n) {
    --channels-default: inherit;
    --interactive-hover: inherit;
    --interactive-active: inherit;
}
```
